# Generated by Django 4.1.4 on 2022-12-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_app_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="container",
            name="stopped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
